### PR TITLE
STYLE: Add ITK prefix to testing macros

### PR DESCRIPTION
**Pull request by jhlegarreta**

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@blowekamp reviews are welcome. Thanks.

**Comment by blowekamp** [comment]
Thanks @jhlegarreta I really appreciate effort in keeping this module up to date. And especially in updating all the remotes in ITK.

 However, here it appears the only line changed is commented out. So they patch is really not needed, and the line should be deleted.

**Comment by jhlegarreta** [comment]
@blowekamp I am aware that in some cases the lines changed are commented (e.g. the [BioCell module](https://github.com/InsightSoftwareConsortium/ITKBioCell/pull/14)), but IMHO considering such cases is beyond the scope of the scripts that apply these changes.

I ignore why it was commented :pensive: . These macros are really useful in testing.

Having a look at the line,  the macro is certainly missing one argument and may be the author commented it to "continue the work at a latter point in time".

In any case, if you want to remove the line, please go ahead and close this PR.

**Comment by blowekamp** [comment]
Thank for the PR again, the line is just being deleted here: #20

**Comment by jhlegarreta** [comment]
OK. You're welcome Brad.

**Pull request closed without merging**
