### PR TITLE
ENH: Require cmake minimum version to be 3.9.5.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Require CMake minimum version to be 3.9.5 following ITKv5 requiring
C++11:
https://discourse.itk.org/t/minimum-cmake-version-update/585

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@blowekamp @zivy The travis error is likely to be related to the docker version. See
https://github.com/InsightSoftwareConsortium/ITKDevelopmentEnvironment/pull/22

**Comment by blowekamp** [comment]
@jhlegarreta 
Thank you for the pull request. I believe I have just fixed some issues with against ITK release, and made now have a patch to update ITK for release:
http://review.source.kitware.com/#/c/23063/

Now we should be able to move forward with ITKv5 requirements.

> @blowekamp @zivy The travis error is likely to be related to the docker version. See
InsightSoftwareConsortium/ITKDevelopmentEnvironment#22

For the above link it is unclear to me what needs to be done in this repository to fix the issue.

**Comment by jhlegarreta** [comment]
I was just guessing, but could updating the `docker` image as in the link provided solve the [travis error](https://travis-ci.org/SimpleITK/ITKSimpleITKFilters/builds/330689318?utm_source=github_status&utm_medium=notification)?

**Comment by jhlegarreta** [comment]
After PR #10 was merged, this does no longer make sense. Closing.

**Pull request closed without merging**
